RateMyHall_App/config/routes.rb
Rails.application.routes.draw do
  get 'dorm_halls/index'
  get 'welcome/index'
  get 'about/index'
  get 'contact/index'
  resources :belk_articles
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RateMyHall_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RateMyHall_App/app/models/belk_article.rb
class BelkArticle < ApplicationRecord
end

RateMyHall_App/app/models/contact.rb
class Contact < ApplicationRecord
end

RateMyHall_App/app/models/welcome.rb
class Welcome < ApplicationRecord
end

RateMyHall_App/app/controllers/about_controller.rb
class AboutController < ApplicationController
end

RateMyHall_App/app/controllers/belk_articles_controller.rb
class BelkArticlesController < ApplicationController
    def new
    end
    
    def create
    @belk_article = BelkArticle.new(belk_article_params)
    
    @belk_article.save
    redirect_to @belk_article
    end
    
    def show
        @belk_article = BelkArticle.find(params[:id])
    end
    
    def index
        @belk_articles = BelkArticle.all
    end
    
    private 
    def belk_article_params
        params.require(:belk_article).permit(:text)
    end
end

RateMyHall_App/app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

RateMyHall_App/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

RateMyHall_App/app/helpers/about_helper.rb
module AboutHelper
end

RateMyHall_App/app/helpers/application_helper.rb
module ApplicationHelper
end

RateMyHall_App/app/helpers/belk_articles_helper.rb
module BelkArticlesHelper
end

RateMyHall_App/app/helpers/contact_helper.rb
module ContactHelper
end

RateMyHall_App/app/helpers/dorm_halls_helper.rb
module DormHallsHelper
end

RateMyHall_App/app/helpers/elm_articles_helper.rb
module ElmArticlesHelper
end

RateMyHall_App/app/helpers/greek_articles_helper.rb
module GreekArticlesHelper
end

RateMyHall_App/app/helpers/hunt_articles_helper.rb
module HuntArticlesHelper
end

RateMyHall_App/app/helpers/laurel_articles_helper.rb
module LaurelArticlesHelper
end

RateMyHall_App/app/helpers/levine_articles_helper.rb
module LevineArticlesHelper
end

RateMyHall_App/app/helpers/lynch_articles_helper.rb
module LynchArticlesHelper
end

RateMyHall_App/app/helpers/oak_articles_helper.rb
module OakArticlesHelper
end

RateMyHall_App/app/helpers/pine_articles_helper.rb
module PineArticlesHelper
end

RateMyHall_App/app/helpers/scott_articles_helper.rb
module ScottArticlesHelper
end

RateMyHall_App/app/helpers/welcome_helper.rb
module WelcomeHelper
end

RateMyHall_App/app/views/belk_articles/index.html.erb
<body1>
<nav class="navigation-bar">
    <img class="logo" src="https://image.flaticon.com/icons/png/512/97/97805.png">
    
    <a href="/welcome/index">Home</a>
    <a href=/about/index>About</a>
    <a href=/dorm_halls/index>Residence Halls</a>
    <a href=/contact/index>Contact Us</a>
</nav>

<body class="belk">
</body>

<div class="row">
  <div class="column">
    <!-- Main Content -->
<div class = "title">
  <h1>Belk Hall</h1>
</div>
 
<div class = "reviews">
    <table align= "center">
  <tr>
    <th>Reviews</th>
  </tr>
 <br>
  <% @belk_articles.each do |belk_article| %>
    <tr>
      <td><%= belk_article.text %></td>
     <!-- <td><%= link_to 'Show', belk_article_path(belk_article) %></td> -->
    </tr>
  <% end %>
</table>
</div>
<h2>
    <%= link_to "Add new review", new_belk_article_path, class:"link"%>
<h2>
  </div>
  <div class="column">
    <div class="mapouter">
   <div class="gmap_canvas">
     <iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=UNCC%20belk%20Hall&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
       
     </iframe><a href="https://www.emojilib.com"></a>
    </div>
  <style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}
  </style>
  <br>
    <strong>Amenities: </strong>
  <ul>Cable TV</ul>
  <ul>Community Kitchen(s)</ul>
  <ul>Community Laundry Room(s)</ul>
  <ul>Community Lounges</ul>
  <ul>Community Study Lounges</ul>
  <ul>Elevator(s)</ul>
  <ul>Gaming Area</ul>
  <ul>Ink Spot Printing</ul>
  <ul>Internet & WiFi</ul>
  <ul>Vending Machines</ul>
</div>
  </div>
</div>

<div class="column">
  
</div>
  </h2>

RateMyHall_App/app/views/belk_articles/new.html.erb
<body1>
<nav class="navigation-bar">
    <img class="logo" src="https://image.flaticon.com/icons/png/512/97/97805.png">
    
    <a href="/welcome/index">Home</a>
    <a href=/about/index>About</a>
    <a href=/dorm_halls/index>Residence Halls</a>
    <a href=/contact/index>Contact Us</a>
</nav>

<body class="belk">
</body>

<!-- Main Content -->
<h1>Belk Hall Page</h1>

<div class="input">
  <%= form_for :belk_article, url: belk_articles_path do |f| %>
  <p>
    <%= f.label :Review %><br> <!-- Label name, change later -->
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

RateMyHall_App/app/views/belk_articles/show.html.erb
<nav class="navigation-bar">
    <img class="logo" src="https://image.flaticon.com/icons/png/512/97/97805.png">
    
    <a href="/welcome/index">Home</a>
    <a href=/about/index>About</a>
    <a href=/dorm_halls/index>Residence Halls</a>
    <a href="#">Contact Us</a>
</nav>

<body class="belk">
</body>
<p>
    <strong>Your Belk Hall Review</strong>
    <%= @belk_article.text %>
</p>

<p1>
  <%= link_to "Return to Belk Hall Page", belk_articles_path, class: "returnLink"%>
</p1>