RateMyHall_App/config/routes.rb
Rails.application.routes.draw do
  get 'dorm_halls/index'
  get 'welcome/index'
  get 'about/index'
  get 'contact/index'
  resources :belk_articles
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RateMyHall_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RateMyHall_App/app/models/belk_article.rb
class BelkArticle < ApplicationRecord
end

RateMyHall_App/app/models/contact.rb
class Contact < ApplicationRecord
end

RateMyHall_App/app/models/welcome.rb
class Welcome < ApplicationRecord
end

RateMyHall_App/app/controllers/about_controller.rb
class AboutController < ApplicationController
end

RateMyHall_App/app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

RateMyHall_App/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

RateMyHall_App/app/helpers/about_helper.rb
module AboutHelper
end

RateMyHall_App/app/helpers/application_helper.rb
module ApplicationHelper
end

RateMyHall_App/app/helpers/belk_articles_helper.rb
module BelkArticlesHelper
end

RateMyHall_App/app/helpers/contact_helper.rb
module ContactHelper
end

RateMyHall_App/app/helpers/dorm_halls_helper.rb
module DormHallsHelper
end

RateMyHall_App/app/helpers/elm_articles_helper.rb
module ElmArticlesHelper
end

RateMyHall_App/app/helpers/greek_articles_helper.rb
module GreekArticlesHelper
end

RateMyHall_App/app/helpers/hunt_articles_helper.rb
module HuntArticlesHelper
end

RateMyHall_App/app/helpers/laurel_articles_helper.rb
module LaurelArticlesHelper
end

RateMyHall_App/app/helpers/levine_articles_helper.rb
module LevineArticlesHelper
end

RateMyHall_App/app/helpers/lynch_articles_helper.rb
module LynchArticlesHelper
end

RateMyHall_App/app/helpers/martin_articles_helper.rb
module MartinArticlesHelper
end

RateMyHall_App/app/helpers/oak_articles_helper.rb
module OakArticlesHelper
end

RateMyHall_App/app/helpers/pine_articles_helper.rb
module PineArticlesHelper
end

RateMyHall_App/app/helpers/scott_articles_helper.rb
module ScottArticlesHelper
end

RateMyHall_App/app/helpers/welcome_helper.rb
module WelcomeHelper
end

RateMyHall_App/app/views/contact/index.html.erb
<body1>
<nav class="navigation-bar">
    <img class="logo" src="https://image.flaticon.com/icons/png/512/97/97805.png">
    
    <a href="/welcome/index">Home</a>
    <a href=/about/index>About</a>
    <a href=/dorm_halls/index>Residence Halls</a>
    <a href=/contact/index>Contact Us</a>
</nav>
<body class="contact">

<div class="container">
  <form action="action_page.php">

    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

    <label for="country">Country</label>
    <select id="country" name="country">
      <option value="usa">USA</option>
      <option value="australia">Australia</option>
      <option value="canada">Canada</option>
    </select>

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <%= link_to "Submit", contact_index_path%>
   

  </form>
</div>

RateMyHall_App/app/views/welcome/index.html.erb
<html>

<head>
<meta charset="utf-8">
<title>Example page</title>
</head>

<body1>
<nav class="navigation-bar">
    <img class="logo" src="https://image.flaticon.com/icons/png/512/97/97805.png">
    
    <a href="/welcome/index">Home</a>
    <a href=/about/index>About</a>
    <a href=/dorm_halls/index>Residence Halls</a>
    <a href=/contact/index>Contact Us</a>
</nav>

<!-- Page content -->


<body class="home">
</body>

<h1 id="box"><br>Rate My Hall</h1>

<h2 id="box">Student driven, 
    unbias college dorm rating platform.</h2>
    
    
</html>